#!/usr/bin/env python3
"""
📦 Embodied Asset Bundle Generator V2.0

SDK-to-MCP V2.0 的具身资产包生成器。
不再只生成单个 .py 文件，而是生成完整的、可发布到 PyPI 的项目结构。

包含:
- 完整的 MCP Server 代码 (符合 6 大 ROSClaw-Native 标准)
- pyproject.toml (现代化 Python 打包)
- README.md (双语文档)
- e_urdf.json (数字孪生配置)
- tests/ (基础测试框架)
- LICENSE (Apache 2.0)
- .gitignore
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class AssetBundleConfig:
    """资产包配置"""
    robot_name: str
    robot_type: str  # "arm", "mobile", "humanoid", "drone"
    vendor: str
    ros_version: str = "humble"

    # MCP 配置
    mcp_server_name: str = ""
    mcp_tools: List[Dict[str, Any]] = field(default_factory=list)

    # 物理参数
    joint_limits: Dict[str, Dict[str, float]] = field(default_factory=dict)
    velocity_limits: Dict[str, float] = field(default_factory=dict)

    # 安全参数
    safety_limits: Dict[str, Any] = field(default_factory=dict)
    collision_pairs: List[List[str]] = field(default_factory=list)

    # 数字孪生
    mujoco_model_path: str = ""
    urdf_path: str = ""

    # ROS 2 接口
    action_servers: List[Dict[str, Any]] = field(default_factory=list)
    services: List[Dict[str, Any]] = field(default_factory=list)
    topics: List[Dict[str, Any]] = field(default_factory=list)
    ros2_interfaces: List[str] = field(default_factory=list)

    # 元数据
    description: str = ""
    version: str = "1.0.0"
    author: str = "ROSClaw Team"

    def __post_init__(self):
        if not self.mcp_server_name:
            self.mcp_server_name = f"rosclaw_{self.robot_name}_mcp"


class EmbodiedAssetBundle:
    """
    具身资产包生成器

    生成完整的、可直接推送到 GitHub 和 PyPI 的项目结构。
    """

    def __init__(self, config: AssetBundleConfig, mcp_code: str):
        self.config = config
        self.mcp_code = mcp_code
        self.base_dir: Optional[Path] = None

    def create_bundle(self, output_dir: str = "generated") -> str:
        """
        创建完整的资产包

        Returns:
            生成的目录路径
        """
        # 创建目录结构
        self.base_dir = Path(output_dir) / self.config.mcp_server_name
        src_dir = self.base_dir / "src" / self.config.mcp_server_name.replace("-", "_")
        tests_dir = self.base_dir / "tests"

        src_dir.mkdir(parents=True, exist_ok=True)
        tests_dir.mkdir(parents=True, exist_ok=True)

        # 1. 写入 MCP Server 代码
        self._write_mcp_server(src_dir)

        # 2. 写入 __init__.py
        self._write_init(src_dir)

        # 3. 写入 pyproject.toml
        self._write_pyproject_toml()

        # 4. 写入 README (双语)
        self._write_readme()

        # 5. 写入 e_urdf.json
        self._write_e_urdf()

        # 6. 写入 LICENSE
        self._write_license()

        # 7. 写入 .gitignore
        self._write_gitignore()

        # 8. 写入测试框架
        self._write_tests(tests_dir)

        return str(self.base_dir)

    def _write_mcp_server(self, src_dir: Path) -> None:
        """写入 MCP Server 主代码"""
        server_file = src_dir / "server.py"
        with open(server_file, "w", encoding="utf-8") as f:
            f.write(self.mcp_code)

    def _write_init(self, src_dir: Path) -> None:
        """写入 __init__.py"""
        init_file = src_dir / "__init__.py"
        robot_class = self._to_class_name(self.config.robot_name)

        content = f'''"""ROSClaw-Native MCP Server for {self.config.robot_name}.

Generated by SDK-to-MCP V2.0 Agentic Compiler on {datetime.now().strftime("%Y-%m-%d")}.

This MCP Server implements all 6 ROSClaw-Native Standards:
- Absolute Async ROS 2 Actions
- Flywheel-Ready JSON Responses
- Digital Twin Firewall Integration
- Graceful Preemption Support
- State-Aware Affordance
- Semantic Spatial Binding
"""

__version__ = "{self.config.version}"
__author__ = "{self.config.author}"
__license__ = "Apache-2.0"

from .server import mcp, ROSClaw{robot_class}Client, ActionResult

__all__ = ["mcp", "ROSClaw{robot_class}Client", "ActionResult"]
'''
        with open(init_file, "w", encoding="utf-8") as f:
            f.write(content)

    def _write_pyproject_toml(self) -> None:
        """写入 pyproject.toml"""
        toml_file = self.base_dir / "pyproject.toml"

        robot_type_keywords = {
            "arm": "manipulation",
            "mobile": "navigation",
            "humanoid": "humanoid",
            "drone": "aerial"
        }

        keyword = robot_type_keywords.get(self.config.robot_type, "robotics")

        content = f'''[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{self.config.mcp_server_name}"
version = "{self.config.version}"
description = "ROSClaw-Native MCP Server for {self.config.vendor} {self.config.robot_name}"
readme = "README.md"
license = {{text = "Apache-2.0"}}
requires-python = ">=3.10"
authors = [
    {{name = "{self.config.author}", email = "contact@rosclaw.org"}},
]
keywords = [
    "ros2",
    "{self.config.robot_type}",
    "{keyword}",
    "mcp",
    "robotics",
    "rosclaw",
    "embodied-ai",
    "{self.config.vendor.lower()}",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Robotics",
]

dependencies = [
    "mcp>=1.0.0",
    "rclpy>=3.0.0",
    "geometry-msgs",
    "sensor-msgs",
    "std-msgs",
    "tf2-ros",
    "rosclaw-firewall>=0.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0",
    "ruff>=0.1.0",
    "mypy>=1.0",
]

[project.scripts]
{self.config.mcp_server_name} = "{self.config.mcp_server_name.replace('-', '_')}.server:mcp.run"

[project.urls]
Homepage = "https://github.com/ros-claw/{self.config.mcp_server_name}"
Documentation = "https://docs.rosclaw.org/{self.config.mcp_server_name}"
Repository = "https://github.com/ros-claw/{self.config.mcp_server_name}"
Issues = "https://github.com/ros-claw/{self.config.mcp_server_name}/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/{self.config.mcp_server_name.replace('-', '_')}"]

[tool.ruff]
target-version = "py310"
line-length = 100
select = ["E", "F", "I", "N", "W", "UP", "B", "C4", "SIM"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = "-v --tb=short"
'''
        with open(toml_file, "w", encoding="utf-8") as f:
            f.write(content)

    def _write_readme(self) -> None:
        """写入双语 README"""
        readme_en = self.base_dir / "README.md"
        readme_zh = self.base_dir / "README.zh.md"

        robot_class = self._to_class_name(self.config.robot_name)

        # 英文 README
        en_content = f'''# ROSClaw-Native {self.config.vendor} {self.config.robot_name} MCP Server

[![ROS 2](https://img.shields.io/badge/ROS_2-{self.config.ros_version.capitalize()}-blue.svg)](https://docs.ros.org)
[![Python](https://img.shields.io/badge/Python-3.10+-blue.svg)](https://www.python.org/)
[![License](https://img.shields.io/badge/License-Apache_2.0-green.svg)](https://opensource.org/licenses/Apache-2.0)
[![MCP](https://img.shields.io/badge/MCP-Protocol-purple.svg)](https://modelcontextprotocol.io/)

> Production-grade MCP server for {self.config.vendor} {self.config.robot_name} with ROSClaw OS integration.
> **"Teach Once, Embody Anywhere. Share Skills, Shape Reality."**

[中文文档](README.zh.md) | [Documentation](https://docs.rosclaw.org/{self.config.mcp_server_name})

---

## Overview

`{self.config.mcp_server_name}` is a ROSClaw-Native MCP server that bridges Large Language Models (LLMs) with {self.config.vendor} {self.config.robot_name} robots.

### Key Features

- **Asynchronous ROS 2 Actions**: Non-blocking action clients with async/await
- **Flywheel-Ready Responses**: Structured JSON for Data Flywheel ingestion
- **Digital Twin Firewall**: MuJoCo-based safety validation
- **Graceful Preemption**: Active task tracking with cancel support
- **State-Aware Affordance**: Local state machine prevents invalid operations
- **Semantic Spatial Binding**: TF2 integration for semantic robot control

---

## Installation

### Prerequisites

- ROS 2 {self.config.ros_version.capitalize()}
- Python 3.10+

### Install from PyPI

```bash
pip install {self.config.mcp_server_name}
```

### Install from Source

```bash
git clone https://github.com/ros-claw/{self.config.mcp_server_name}.git
cd {self.config.mcp_server_name}
pip install -e ".[dev]"
```

---

## Quick Start

### 1. Start ROS 2

```bash
source /opt/ros/{self.config.ros_version}/setup.bash
ros2 launch your_robot_bringup robot.launch.py
```

### 2. Start the MCP Server

```bash
{self.config.mcp_server_name}
```

### 3. Configure MCP Client

```json
{{
  "mcpServers": {{
    "{self.config.mcp_server_name}": {{
      "command": "{self.config.mcp_server_name}",
      "transportType": "stdio"
    }}
  }}
}}
```

---

## ROSClaw-Native Standards

This MCP Server implements all 6 ROSClaw-Native Standards:

1. ✅ **Absolute Async** - All actions use async/await
2. ✅ **Flywheel-Ready JSON** - Structured responses for Data Flywheel
3. ✅ **Firewall Integration** - `@mujoco_firewall` for physical safety
4. ✅ **Graceful Preemption** - Task cancellation support
5. ✅ **State-Aware** - Prevents invalid concurrent operations
6. ✅ **Semantic Spatial Binding** - TF2 integration

---

## License

Apache License 2.0 - See [LICENSE](LICENSE)

---

<p align="center">
  <strong>ROSClaw - Embodied Intelligence Operating System</strong><br>
  <em>Teach Once, Embody Anywhere. Share Skills, Shape Reality.</em>
</p>
'''

        # 中文 README
        zh_content = f'''# ROSClaw-Native {self.config.vendor} {self.config.robot_name} MCP 服务器

[![ROS 2](https://img.shields.io/badge/ROS_2-{self.config.ros_version.capitalize()}-blue.svg)](https://docs.ros.org)
[![Python](https://img.shields.io/badge/Python-3.10+-blue.svg)](https://www.python.org/)
[![License](https://img.shields.io/badge/License-Apache_2.0-green.svg)](https://opensource.org/licenses/Apache-2.0)
[![MCP](https://img.shields.io/badge/MCP-Protocol-purple.svg)](https://modelcontextprotocol.io/)

> 生产级 {self.config.vendor} {self.config.robot_name} MCP 服务器，深度集成 ROSClaw 具身智能操作系统
> **"教导一次，任意实体运行。共享技能，重塑现实。"**

[English Documentation](README.md) | [官方文档](https://docs.rosclaw.org/{self.config.mcp_server_name})

---

## 概述

`{self.config.mcp_server_name}` 是一个 ROSClaw-Native MCP 服务器，它架起了大型语言模型（LLM）与 {self.config.vendor} {self.config.robot_name} 机器人之间的桥梁。

### 核心特性

- **异步 ROS 2 动作**：使用 async/await 的非阻塞动作客户端
- **飞轮就绪响应**：结构化 JSON，支持数据飞轮自动采集
- **数字孪生防火墙**：真实执行前基于 MuJoCo 的安全验证
- **优雅抢占**：支持任务取消的活动任务跟踪
- **状态感知交互**：本地状态机防止无效操作
- **语义空间绑定**：TF2 集成用于语义机器人控制

---

## 安装

### 前置要求

- ROS 2 {self.config.ros_version.capitalize()}
- Python 3.10+

### 从 PyPI 安装

```bash
pip install {self.config.mcp_server_name}
```

### 从源码安装

```bash
git clone https://github.com/ros-claw/{self.config.mcp_server_name}.git
cd {self.config.mcp_server_name}
pip install -e ".[dev]"
```

---

## 快速开始

### 1. 启动 ROS 2

```bash
source /opt/ros/{self.config.ros_version}/setup.bash
ros2 launch your_robot_bringup robot.launch.py
```

### 2. 启动 MCP 服务器

```bash
{self.config.mcp_server_name}
```

### 3. 配置 MCP 客户端

```json
{{
  "mcpServers": {{
    "{self.config.mcp_server_name}": {{
      "command": "{self.config.mcp_server_name}",
      "transportType": "stdio"
    }}
  }}
}}
```

---

## ROSClaw-Native 六大标准

本 MCP 服务器实现了全部 6 大 ROSClaw-Native 标准：

1. ✅ **绝对异步** - 所有动作使用 async/await
2. ✅ **飞轮就绪 JSON** - 结构化响应支持数据飞轮
3. ✅ **防火墙集成** - `@mujoco_firewall` 确保物理安全
4. ✅ **优雅抢占** - 支持任务取消
5. ✅ **状态感知** - 防止无效并发操作
6. ✅ **语义空间绑定** - TF2 集成

---

## 许可证

Apache License 2.0 - 详见 [LICENSE](LICENSE)

---

<p align="center">
  <strong>ROSClaw - 具身智能操作系统</strong><br>
  <em>教导一次，任意实体运行。共享技能，重塑现实。</em>
</p>
'''

        with open(readme_en, "w", encoding="utf-8") as f:
            f.write(en_content)
        with open(readme_zh, "w", encoding="utf-8") as f:
            f.write(zh_content)

    def _write_e_urdf(self) -> None:
        """写入 e_urdf.json 数字孪生配置"""
        e_urdf_file = self.base_dir / "e_urdf.json"

        e_urdf_data = {
            "version": "2.0",
            "robot": {
                "name": self.config.robot_name,
                "vendor": self.config.vendor,
                "type": self.config.robot_type,
            },
            "digital_twin": {
                "mujoco_model": self.config.mujoco_model_path,
                "urdf": self.config.urdf_path,
            },
            "kinematics": {
                "joint_limits": self.config.joint_limits,
                "velocity_limits": self.config.velocity_limits,
            },
            "safety": {
                "limits": self.config.safety_limits,
                "collision_pairs": self.config.collision_pairs,
            },
            "ros2_interfaces": {
                "action_servers": self.config.action_servers,
                "services": self.config.services,
                "topics": self.config.topics,
            },
            "mcp_server": {
                "name": self.config.mcp_server_name,
                "tools": [tool.get("name", "unknown") for tool in self.config.mcp_tools],
            }
        }

        with open(e_urdf_file, "w", encoding="utf-8") as f:
            json.dump(e_urdf_data, f, indent=2, ensure_ascii=False)

    def _write_license(self) -> None:
        """写入 Apache 2.0 LICENSE"""
        license_file = self.base_dir / "LICENSE"

        content = f'''                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   Copyright 2025 ROSClaw Team

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
'''
        with open(license_file, "w", encoding="utf-8") as f:
            f.write(content)

    def _write_gitignore(self) -> None:
        """写入 .gitignore"""
        gitignore_file = self.base_dir / ".gitignore"

        content = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# ROS 2
install/
log/
build/
.colcon/

# Testing
.coverage
.pytest_cache/
htmlcov/
.tox/

# OS
.DS_Store
Thumbs.db

# Project specific
*.log
config/local.yaml
'''
        with open(gitignore_file, "w", encoding="utf-8") as f:
            f.write(content)

    def _write_tests(self, tests_dir: Path) -> None:
        """写入测试框架"""
        init_file = tests_dir / "__init__.py"
        test_file = tests_dir / "test_server.py"

        with open(init_file, "w", encoding="utf-8") as f:
            f.write('"""Tests for {}.""".\n'.format(self.config.mcp_server_name))

        robot_class = self._to_class_name(self.config.robot_name)

        content = f'''"""Tests for {self.config.mcp_server_name} server."""

import pytest
from {self.config.mcp_server_name.replace("-", "_")} import __version__, mcp, ROSClaw{robot_class}Client


def test_version():
    """Test version is defined."""
    assert __version__ == "{self.config.version}"


def test_imports():
    """Test main imports work."""
    assert mcp is not None
    assert ROSClaw{robot_class}Client is not None


@pytest.mark.asyncio
async def test_client_initialization():
    """Test client can be initialized."""
    # Note: This requires ROS 2 environment
    # client = ROSClaw{robot_class}Client()
    # await client.start()
    # await client.stop()
    pass
'''
        with open(test_file, "w", encoding="utf-8") as f:
            f.write(content)

    def _to_class_name(self, name: str) -> str:
        """将 snake_case 转换为 CamelCase"""
        return ''.join(word.capitalize() for word in name.split('_'))


def create_embodied_asset_bundle(
    robot_name: str,
    mcp_code: str,
    robot_type: str = "arm",
    vendor: str = "Generic",
    **kwargs
) -> str:
    """
    快速创建具身资产包的入口函数

    Args:
        robot_name: 机器人名称
        mcp_code: 生成的 MCP Server 代码
        robot_type: 机器人类型 (arm/mobile/humanoid/drone)
        vendor: 厂商名称
        **kwargs: 其他配置参数

    Returns:
        生成的目录路径
    """
    config = AssetBundleConfig(
        robot_name=robot_name,
        robot_type=robot_type,
        vendor=vendor,
        **kwargs
    )

    bundle = EmbodiedAssetBundle(config, mcp_code)
    return bundle.create_bundle()


if __name__ == "__main__":
    # 测试用例
    test_code = '''
#!/usr/bin/env python3
"""Test MCP Server."""
from mcp.server.fastmcp import FastMCP
mcp = FastMCP("test")
'''

    path = create_embodied_asset_bundle(
        robot_name="test_bot",
        mcp_code=test_code,
        robot_type="arm",
        vendor="TestCorp"
    )
    print(f"Bundle created at: {path}")
