"""
MCP 代码生成器 (Generator)

基于 Jinja2 模板，将协议模式渲染为可运行的 MCP Server 代码。
"""

import os
from pathlib import Path
from typing import Dict, Any, Literal
from jinja2 import Environment, FileSystemLoader, PackageLoader


class MCPGenerator:
    """
    MCP Server 代码生成器

    支持多种硬件通信类型的模板：
    - serial: 串口/字节流协议
    - dds: DDS 分布式通信
    - ros: ROS/ROS2 接口
    - http: HTTP/REST API
    """

    def __init__(self):
        self.template_dir = Path(__file__).parent.parent / "templates"
        self.jinja_env = Environment(
            loader=FileSystemLoader(str(self.template_dir)),
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True
        )

    async def generate(
        self,
        schema: Dict[str, Any],
        hardware_type: Literal['serial', 'dds', 'ros', 'http'],
        target_name: str
    ) -> str:
        """
        生成 MCP Server 代码。

        Args:
            schema: 协议模式定义
            hardware_type: 硬件通信类型
            target_name: MCP Server 名称

        Returns:
            生成的 Python 代码
        """
        template_name = f"{hardware_type}_mcp.jinja2"
        template_path = self.template_dir / template_name

        # 如果模板不存在，使用基础模板
        if not template_path.exists():
            print(f"   ⚠ 模板 {template_name} 不存在，使用基础模板")
            template_name = "base_mcp.jinja2"

        try:
            template = self.jinja_env.get_template(template_name)
        except Exception:
            # 如果连基础模板都不存在，使用内联模板
            template = self.jinja_env.from_string(self._get_inline_template(hardware_type))

        # 准备模板上下文
        context = {
            "target_name": target_name,
            "server_class_name": self._to_class_name(target_name),
            "actions": schema.get("actions", []),
            "states": schema.get("states", []),
            "protocol_details": schema.get("protocol_details", {}),
            "hardware_info": schema.get("hardware_info", {})
        }

        # 渲染模板
        code = template.render(**context)
        return code

    def _to_class_name(self, name: str) -> str:
        """将 snake_case 转换为 PascalCase"""
        parts = name.replace("-", "_").split("_")
        return "".join(part.capitalize() for part in parts)

    def _get_inline_template(self, hardware_type: str) -> str:
        """获取内联模板（模板文件不存在时使用）"""

        base_template = '''"""
{{ target_name }} MCP Server

Auto-generated by sdk-to-mcp Skill
Hardware Type: {{ hardware_type }}
"""

import asyncio
import struct
from typing import Optional, Dict, Any
from mcp.server.fastmcp import FastMCP

# Initialize MCP Server
mcp = FastMCP("{{ target_name }}")


class {{ server_class_name }}Bridge:
    """
    Hardware communication bridge
    """

    def __init__(self):
        self.connected = False
        {% if protocol_details.safety_limits %}
        self.safety_limits = {{ protocol_details.safety_limits | tojson }}
        {% else %}
        self.safety_limits = {}
        {% endif %}

    def connect(self) -> bool:
        """Connect to hardware"""
        # TODO: Implement hardware connection
        self.connected = True
        return True

    def disconnect(self):
        """Disconnect from hardware"""
        self.connected = False

    def _validate_safety(self, **kwargs) -> tuple[bool, str]:
        """Validate parameters against safety limits"""
        {% if protocol_details.safety_limits %}
        {% for limit, value in protocol_details.safety_limits.items() %}
        if "{{ limit }}" in kwargs:
            val = kwargs["{{ limit }}"]
            if abs(val) > {{ value }}:
                return False, f"{{ limit }} exceeds safety limit: {{ value }}"
        {% endfor %}
        {% endif %}
        return True, "OK"


# Global bridge instance
_bridge = {{ server_class_name }}Bridge()

{% for action in actions %}
@mcp.tool()
async def {{ action.name }}({% for param, ptype in action.params.items() %}{{ param }}: {{ ptype }}{% if not loop.last %}, {% endif %}{% endfor %}) -> str:
    """
    {{ action.description }}

    Args:
        {% for param, ptype in action.params.items() %}
        {{ param }}: Parameter of type {{ ptype }}
        {% endfor %}

    Returns:
        Operation result message
    """
    if not _bridge.connected:
        await asyncio.sleep(0.1)  # Simulate connection check

    # Safety validation
    valid, msg = _bridge._validate_safety({% for param in action.params.keys() %}{{ param }}={{ param }}{% if not loop.last %}, {% endif %}{% endfor %})
    if not valid:
        return f"Safety check failed: {msg}"

    # TODO: Implement actual hardware command
    return f"Executed {{ action.name }}"

{% endfor %}

{% for state in states %}
@mcp.resource("{{ state.name }}://status")
async def get_{{ state.name }}() -> str:
    """
    {{ state.description }}
    {% if state.unit %}Unit: {{ state.unit }}{% endif %}
    """
    # TODO: Implement actual state reading
    return f"{{ state.name }}: reading..."

{% endfor %}


if __name__ == "__main__":
    mcp.run(transport="stdio")
'''
        return base_template
