// Auto-generated by HubSyncPublisher
// DO NOT EDIT MANUALLY

export interface Robot {
  id: string;
  name: string;
  vendor: string;
  type: 'arm' | 'mobile' | 'humanoid' | 'drone';
  description: string;
  githubUrl: string;
  docsUrl: string;
  tools: string[];
  safetyLevel: string;
  status: string;
}

export const robots: Robot[] = [
  {
    id: "unitree_unitree_go2",
    name: "Unitree Unitree Go2",
    vendor: "Unitree",
    type: "mobile",
    description: "...",
    githubUrl: "https://github.com/ros-claw/rosclaw_unitree_go2_mcp",
    docsUrl: "",
    tools: ["walk", "stand_up", "get_battery"],
    safetyLevel: "STRICT",
    status: "beta",
  },
];